Make a blob's time living have less of an effect on its fitness value
ERROR: For some reason, modification of Blob::calcFitness causes almost
all blobs to move to the right. Previously, blob movement was less uniform
on creating a new world. Even worse, evolution does not seem to be able to
weed out this behavior.